package com.opencodejava.tool;

import com.opencodejava.provider.LLMProvider.ToolDefinition;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Image generation tool that creates SVG files based on a description.
 * Generates vector graphics without requiring external API keys.
 */
public class ImageGenTool implements Tool {

    @Override
    public String getName() { return "image_gen"; }

    @Override
    public String getDescription() {
        return "Generate an SVG image file based on a text description. " +
                "Creates vector graphics (logos, diagrams, icons, simple illustrations). " +
                "Specify the description and output path.";
    }

    @Override
    public ToolResult execute(Map<String, Object> arguments) {
        String description = (String) arguments.get("description");
        String outputPath = (String) arguments.get("path");

        if (description == null || description.isEmpty()) {
            return ToolResult.failure("Missing required argument: description");
        }
        if (outputPath == null || outputPath.isEmpty()) {
            outputPath = "generated_image.svg";
        }

        if (!outputPath.endsWith(".svg")) {
            outputPath += ".svg";
        }

        try {
            String svg = generateSvg(description);
            Path path = Path.of(outputPath).toAbsolutePath();

            Path parent = path.getParent();
            if (parent != null && !Files.exists(parent)) {
                Files.createDirectories(parent);
            }

            Files.writeString(path, svg);
            return ToolResult.success("Generated SVG image at: " + path + "\nDescription: " + description +
                    "\nSize: " + svg.length() + " bytes");
        } catch (IOException e) {
            return ToolResult.failure("Failed to generate image: " + e.getMessage());
        }
    }

    /**
     * Generates an SVG based on the description.
     * Creates a meaningful SVG with shapes, gradients, and text based on keywords.
     */
    private String generateSvg(String description) {
        String lower = description.toLowerCase();
        int width = 400;
        int height = 300;

        StringBuilder svg = new StringBuilder();
        svg.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        svg.append("<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 ")
                .append(width).append(" ").append(height).append("\" width=\"")
                .append(width).append("\" height=\"").append(height).append("\">\n");

        // Add metadata
        svg.append("  <!-- Generated by OpenCode Java ImageGenTool -->\n");
        svg.append("  <!-- Description: ").append(escapeXml(description)).append(" -->\n");

        // Background gradient
        svg.append("  <defs>\n");
        svg.append("    <linearGradient id=\"bg\" x1=\"0%\" y1=\"0%\" x2=\"100%\" y2=\"100%\">\n");

        if (lower.contains("dark") || lower.contains("night")) {
            svg.append("      <stop offset=\"0%\" style=\"stop-color:#1a1a2e\"/>\n");
            svg.append("      <stop offset=\"100%\" style=\"stop-color:#16213e\"/>\n");
        } else if (lower.contains("sunset") || lower.contains("warm")) {
            svg.append("      <stop offset=\"0%\" style=\"stop-color:#ff6b6b\"/>\n");
            svg.append("      <stop offset=\"100%\" style=\"stop-color:#feca57\"/>\n");
        } else if (lower.contains("ocean") || lower.contains("water") || lower.contains("blue")) {
            svg.append("      <stop offset=\"0%\" style=\"stop-color:#667eea\"/>\n");
            svg.append("      <stop offset=\"100%\" style=\"stop-color:#764ba2\"/>\n");
        } else if (lower.contains("nature") || lower.contains("green") || lower.contains("forest")) {
            svg.append("      <stop offset=\"0%\" style=\"stop-color:#56ab2f\"/>\n");
            svg.append("      <stop offset=\"100%\" style=\"stop-color:#a8e063\"/>\n");
        } else {
            svg.append("      <stop offset=\"0%\" style=\"stop-color:#4facfe\"/>\n");
            svg.append("      <stop offset=\"100%\" style=\"stop-color:#00f2fe\"/>\n");
        }

        svg.append("    </linearGradient>\n");
        svg.append("  </defs>\n");

        // Background
        svg.append("  <rect width=\"100%\" height=\"100%\" fill=\"url(#bg)\"/>\n");

        // Generate shapes based on description keywords
        if (lower.contains("logo") || lower.contains("icon")) {
            generateLogo(svg, description, width, height);
        } else if (lower.contains("chart") || lower.contains("graph")) {
            generateChart(svg, width, height);
        } else if (lower.contains("diagram") || lower.contains("flow")) {
            generateDiagram(svg, width, height);
        } else {
            generateAbstract(svg, description, width, height);
        }

        // Add title text
        svg.append("  <text x=\"").append(width / 2).append("\" y=\"").append(height - 20)
                .append("\" text-anchor=\"middle\" font-family=\"Arial, sans-serif\" ")
                .append("font-size=\"12\" fill=\"rgba(255,255,255,0.7)\">")
                .append(escapeXml(truncate(description, 50))).append("</text>\n");

        svg.append("</svg>\n");
        return svg.toString();
    }

    private void generateLogo(StringBuilder svg, String description, int width, int height) {
        int cx = width / 2;
        int cy = height / 2 - 20;

        svg.append("  <circle cx=\"").append(cx).append("\" cy=\"").append(cy)
                .append("\" r=\"60\" fill=\"white\" opacity=\"0.9\"/>\n");
        svg.append("  <circle cx=\"").append(cx).append("\" cy=\"").append(cy)
                .append("\" r=\"50\" fill=\"none\" stroke=\"#333\" stroke-width=\"3\"/>\n");

        // Add initial letter
        String initial = description.replaceAll("[^a-zA-Z]", "").substring(0, 1).toUpperCase();
        svg.append("  <text x=\"").append(cx).append("\" y=\"").append(cy + 15)
                .append("\" text-anchor=\"middle\" font-family=\"Arial\" font-size=\"48\" ")
                .append("font-weight=\"bold\" fill=\"#333\">").append(initial).append("</text>\n");
    }

    private void generateChart(StringBuilder svg, int width, int height) {
        int[] values = {60, 120, 80, 150, 100, 130, 90};
        int barWidth = 30;
        int gap = 15;
        int startX = 60;
        String[] colors = {"#ff6b6b", "#feca57", "#48dbfb", "#ff9ff3", "#54a0ff", "#5f27cd", "#01a3a4"};

        for (int i = 0; i < values.length; i++) {
            int x = startX + i * (barWidth + gap);
            int barHeight = values[i];
            int y = height - 50 - barHeight;
            svg.append("  <rect x=\"").append(x).append("\" y=\"").append(y)
                    .append("\" width=\"").append(barWidth).append("\" height=\"").append(barHeight)
                    .append("\" fill=\"").append(colors[i]).append("\" rx=\"3\"/>\n");
        }
    }

    private void generateDiagram(StringBuilder svg, int width, int height) {
        int[][] boxes = {{50, 80}, {170, 80}, {290, 80}, {110, 180}, {230, 180}};
        String[] labels = {"A", "B", "C", "D", "E"};

        for (int i = 0; i < boxes.length; i++) {
            svg.append("  <rect x=\"").append(boxes[i][0]).append("\" y=\"").append(boxes[i][1])
                    .append("\" width=\"60\" height=\"40\" rx=\"5\" fill=\"white\" opacity=\"0.9\" stroke=\"#333\"/>\n");
            svg.append("  <text x=\"").append(boxes[i][0] + 30).append("\" y=\"").append(boxes[i][1] + 25)
                    .append("\" text-anchor=\"middle\" font-family=\"Arial\" font-size=\"16\" fill=\"#333\">")
                    .append(labels[i]).append("</text>\n");
        }

        // Connecting lines
        svg.append("  <line x1=\"80\" y1=\"120\" x2=\"140\" y2=\"180\" stroke=\"white\" stroke-width=\"2\"/>\n");
        svg.append("  <line x1=\"200\" y1=\"120\" x2=\"140\" y2=\"180\" stroke=\"white\" stroke-width=\"2\"/>\n");
        svg.append("  <line x1=\"200\" y1=\"120\" x2=\"260\" y2=\"180\" stroke=\"white\" stroke-width=\"2\"/>\n");
        svg.append("  <line x1=\"320\" y1=\"120\" x2=\"260\" y2=\"180\" stroke=\"white\" stroke-width=\"2\"/>\n");
    }

    private void generateAbstract(StringBuilder svg, String description, int width, int height) {
        // Generate decorative circles based on description hash
        int hash = description.hashCode();
        for (int i = 0; i < 5; i++) {
            int cx = 50 + Math.abs((hash + i * 73) % (width - 100));
            int cy = 50 + Math.abs((hash + i * 97) % (height - 100));
            int r = 20 + Math.abs((hash + i * 31) % 40);
            float opacity = 0.2f + (Math.abs((hash + i * 53) % 5) * 0.1f);
            svg.append("  <circle cx=\"").append(cx).append("\" cy=\"").append(cy)
                    .append("\" r=\"").append(r).append("\" fill=\"white\" opacity=\"")
                    .append(opacity).append("\"/>\n");
        }

        // Center text
        svg.append("  <text x=\"").append(width / 2).append("\" y=\"").append(height / 2)
                .append("\" text-anchor=\"middle\" font-family=\"Arial\" font-size=\"24\" ")
                .append("font-weight=\"bold\" fill=\"white\">")
                .append(escapeXml(truncate(description, 30))).append("</text>\n");
    }

    private String escapeXml(String text) {
        return text.replace("&", "&amp;").replace("<", "&lt;")
                .replace(">", "&gt;").replace("\"", "&quot;");
    }

    private String truncate(String text, int maxLen) {
        return text.length() <= maxLen ? text : text.substring(0, maxLen - 3) + "...";
    }

    @Override
    public ToolDefinition getDefinition() {
        Map<String, Object> params = new LinkedHashMap<>();
        params.put("description", Map.of("type", "string",
                "description", "Description of the image to generate (e.g., 'a blue logo with a lightning bolt')"));
        params.put("path", Map.of("type", "string",
                "description", "Output file path for the SVG (defaults to generated_image.svg)"));
        return new ToolDefinition(getName(), getDescription(), params);
    }

    @Override
    public boolean isReadOnly() { return false; }
}
